# Generated by Django 5.0.6 on 2024-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprietorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_recto', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('cni_verso', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('facture_recto', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('facture_verso', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
