# Generated by Django 5.0.6 on 2024-06-15 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_proprietorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
