# Generated by Django 5.0.6 on 2024-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date_visit',
            new_name='date_1',
        ),
        migrations.AddField(
            model_name='visit',
            name='date_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='date_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
