# Generated by Django 5.0.6 on 2024-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_date_visit_visit_date_1_visit_date_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_status',
            field=models.TextField(choices=[('PE', 'Pending'), ('C', 'Confirmed'), ('PA', 'Passed'), ('O', 'On going')], default='PE', max_length=2),
        ),
    ]
