# Generated by Django 5.0.6 on 2024-06-20 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_visit_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='date_held',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
