# Generated by Django 5.0.6 on 2024-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_title', models.FileField(upload_to='land_titles/')),
                ('property_type', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('neighborood', models.CharField(max_length=100)),
                ('standing', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
