# Generated by Django 5.0.6 on 2024-06-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'propertie'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='neighborood',
            new_name='neighbohood',
        ),
    ]
