# Generated by Django 5.0.6 on 2024-06-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_and_more'),
        ('users', '0006_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='proprietor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.proprietorprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='users.buyerprofile'),
        ),
    ]
