# Generated by Django 5.0.6 on 2024-06-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_proprietor_property_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.TextField(choices=[('LVR', 'Living Room'), ('BDR', 'Bed Room'), ('KIT', 'Kietchen'), ('BAL', 'Balcony')], default='LVR', max_length=3)),
                ('image', models.ImageField(upload_to='property_rooms/')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
        ),
    ]
