# Generated by Django 5.0.6 on 2024-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('A', 'Apartment'), ('FA', 'Furnished Apartment'), ('R', 'Room'), ('S', 'Studio')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='standing',
            field=models.CharField(choices=[('P', 'Premium'), ('H', 'Hight'), ('S', 'Standard')], default='S', max_length=1),
        ),
    ]
