# Generated by Django 5.0.6 on 2024-06-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_property_type_alter_property_standing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='neighbohood',
            new_name='neighborhood',
        ),
    ]
