# Generated by Django 5.0.6 on 2024-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_neighbohood_property_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('A', 'Aproved'), ('P', 'PENDING')], default='P', max_length=100),
        ),
    ]
